### ISSUE TITLE
How can I call and use it in DBeaver to export query result to a Parquet file?

### ISSUE THREAD

**Issue by coloraven** [manticore-projects/JDBCParquetWriter#3]
This is exactly what I have been looking for, but I don't know how to use it. Is it a DBeaver plugin? If there is a tutorial on how to use it, I think it would be beneficial to more people，especially for those buddy like me which don't understand Java.

**Comment by sirliu** [comment]
> This is exactly what I have been looking for, but I don't know how to use it. Is it a DBeaver plugin? If there is a tutorial on how to use it, I think it would be beneficial to more people，especially for those buddy like me which don't understand Java.
 

according the readme ，h know this is a JAVA library，but not a dbeaver plugin。

**Comment by manticore-projects** [comment]
Greetings!

It should be possible to wrap this into a minimal DBeaver Plugin. I would give it a try, without any promise.

**Comment by manticore-projects** [comment]
This should be solved since DBeaver supports Parquet files now.
