### ISSUE TITLE
Feature request:  return number of rows written

### ISSUE THREAD

**Issue by amoGLingle** [manticore-projects/JDBCParquetWriter#5]
Would be good if this returned the number of rows written to the file.
Guess I could submit a PR.
Thanks.

**Comment by manticore-projects** [comment]
Thank you for your suggestion.
Cheers!

**Comment by amoGLingle** [comment]
Nice! Thanks Andreas. I see you've updated.
Oh. Seems you missed on lines 136/7, not that I'm using that function :).

Any chance of getting this into Maven Central soon?  Else i'll just pull this into my repo local until its up.
Thanks again.

**Comment by manticore-projects** [comment]
Thanks for pointing out the miss, I would fix it.
I will add SonaType/Snapshots tomorrow.

**Comment by manticore-projects** [comment]
Fixed.

And here are the SonaType Snapshot coordinates: https://manticore-projects.com/JDBCParquetWriter/usage.html#build-dependencies
