### ISSUE TITLE
wrong mapping of Oracle number

### ISSUE THREAD

**Issue by molok** [manticore-projects/JDBCParquetWriter#8]
Oracle returns -127 as the scale when the scale isn't specified in the table

see: https://docs.oracle.com/database/121/JAJDB/oracle/jdbc/OracleResultSetMetaData.html#isVariableScale_int_

the code doesn't handle this gracefully, it transform the data into INT32

**Comment by manticore-projects** [comment]
Greetings!

Thank you for reporting, I will try to reproduce and provide a fix.
Oracle Object Mapping always has been nuts unfortunately.

Any chance you can provide a Table DDL statement for a quick test case please?

**Comment by molok** [comment]
yeah, Oracle object mapping is hell, this is an example:

`create table my_test ( my_value number );`

on the database this is like a number(38, 10) (I'm not sure if this is always the case) but in the jdbc metadata it returns scale -127 and precision 0 (WTF)

a quick and dirty workaround is to cast the column to number(38, 10), e.g.:

`select cast(my_value as number(38, 10)) as my_value from my_test`

**Comment by manticore-projects** [comment]
I have to confess: I actually did not know that and would have expected  to see the 38 and 10 in the result set meta data.
Guess, I will need to come up with some additional, oracle specific tests.

If you ask me, this is a Oracle bug -- but of course this does not help anyone.
What Oracle JDBC driver have you tested? I know that those OJDBC versions come all with their own set of errors and unexpected behavior.

**Comment by molok** [comment]
it's documented, so it's not a bug (but it's weird): https://docs.oracle.com/database/121/JAJDB/oracle/jdbc/OracleResultSetMetaData.html#isVariableScale_int_

a more important issue is that even when the scale/precision is specified the value seems to be wrong:

https://github.com/manticore-projects/JDBCParquetWriter/blob/e0eac8d8596a29e5aad795221ce853432acdf56c/src/main/java/com/manticore/jdbc/parquetwriter/JDBCParquetWriter.java#L289-L291

the scale of decimal is wrong, it should be

``` java
     BigDecimal decimal = rs.getBigDecimal(i).setScale(scale); 
```

**Comment by manticore-projects** [comment]
Sorry for taking so long. There is a chance that I got this fixed, would you like to give it a try please?!
Thank you a lot in advance and cheers.
